#Kabanero! on activate substitute Digest for text '@Digest@'
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener-@Digest@
spec:
  serviceAccountName: tekton-webhooks-extension-eventlistener
  triggers:
  - bindings:
    - apiversion: v1alpha1
      name: build-pl-@Digest@-push-binding
    interceptors:
    - cel:
        filter: 'body["webhooks-tekton-event-type"] == "push" '
    name: kabanero-push-event
    template:
      apiversion: v1alpha1
      name: build-pl-@Digest@-template
  - bindings:
    - apiversion: v1alpha1
      name: build-push-deploy-pl-@Digest@-pullrequest-binding
    interceptors:
    - cel:
        filter: 'body["webhooks-tekton-event-type"] == "pull_request" '
    name: kabanero-pullrequest-event
    template:
      apiversion: v1alpha1
      name: build-push-deploy-pl-@Digest@-template
  - bindings:
    - apiversion: v1alpha1
      name: image-retag-pl-@Digest@-pullrequest-binding
    interceptors:
    - cel:
        filter: 'body["webhooks-tekton-event-type"] == "tag" '
    name: kabanero-pullrequest-event
    template:
      apiversion: v1alpha1
      name: image-retag-pl-@Digest@-template
  - bindings:
    - apiversion: v1alpha1
      name: monitor-task-github-@Digest@-binding
    template:
     apiversion: v1alpha1
     name: monitor-task-@Digest@-template
    name: kabanero-monitor-task-event
    interceptors:
      - cel:
          filter: 'body["webhooks-tekton-monitor"] '